@echo off
REM ============================================================
REM Build CLI Steering — Assembles all per-repo steering docs
REM into a single master file for use by kiro-cli.
REM
REM This script reads .kiro/steering/*.md from every monitored
REM repo and concatenates them into one file, adding separators
REM and source annotations so Kiro knows where each doc came from.
REM
REM Excludes:
REM   - Files with "inclusion: manual" in front-matter (opt-in only)
REM   - Duplicate github-issue-workflow.md (uses Game-Dev-Supreme's
REM     as the canonical copy since it's the most up-to-date)
REM
REM Output: %WORK_DIR%\cli-steering-combined.md
REM ============================================================

setlocal enabledelayedexpansion

set "WORK_DIR=c:\Users\Daniel Sawitzki\Desktop\github\Game-Dev-Supreme"
set "OUTPUT=%WORK_DIR%\cli-steering-combined.md"
set "GITHUB_ROOT=c:\Users\Daniel Sawitzki\Desktop\github"

REM Define repos and their local folder names
set "REPO_1=Game-Dev-Supreme"
set "REPO_2=Zeitgeist Evolved"
set "REPO_3=SDL_VisualTest"
set "REPO_4=Super Civ 16"
set "REPO_5=TerrorForm"

REM Start with a header
echo # Combined CLI Steering Context> "%OUTPUT%"
echo.>> "%OUTPUT%"
echo ^> Auto-generated by build-cli-steering.bat. Do not edit manually.>> "%OUTPUT%"
echo ^> Generated: %date% %time%>> "%OUTPUT%"
echo.>> "%OUTPUT%"
echo This file consolidates all workspace steering docs from every monitored>> "%OUTPUT%"
echo repository so that headless kiro-cli runs have the same context as the>> "%OUTPUT%"
echo IDE multi-repo workspace.>> "%OUTPUT%"
echo.>> "%OUTPUT%"
echo --->> "%OUTPUT%"
echo.>> "%OUTPUT%"

REM Track which filenames we've already included (deduplicate across repos).
REM Repos are processed in priority order — Game-Dev-Supreme first (canonical
REM workflow doc), then Zeitgeist Evolved (richest project-specific docs),
REM then the rest. First occurrence of each filename wins.
set "INCLUDED_FILES="

REM Process each repo
for %%R in (1 2 3 4 5) do (
    set "REPO_NAME=!REPO_%%R!"
    set "STEERING_DIR=%GITHUB_ROOT%\!REPO_NAME!\.kiro\steering"

    if exist "!STEERING_DIR!" (
        for %%F in ("!STEERING_DIR!\*.md") do (
            set "FILENAME=%%~nxF"
            set "FILEPATH=%%F"
            set "SKIP=0"

            REM Skip if this filename was already included from a higher-priority repo
            echo !INCLUDED_FILES! | findstr /i /c:"[!FILENAME!]" >nul 2>&1
            if not errorlevel 1 (
                set "SKIP=1"
                echo   [Skipped - duplicate] !REPO_NAME!\!FILENAME!
            )

            REM Check for "inclusion: manual" — skip those files
            if !SKIP!==0 (
                findstr /i /c:"inclusion: manual" "!FILEPATH!" >nul 2>&1
                if not errorlevel 1 (
                    set "SKIP=1"
                    echo   [Skipped - manual inclusion] !REPO_NAME!\!FILENAME!
                )
            )

            if !SKIP!==0 (
                echo   [Including] !REPO_NAME!\!FILENAME!
                set "INCLUDED_FILES=!INCLUDED_FILES![!FILENAME!]"
                echo ## Source: !REPO_NAME! / !FILENAME!>> "%OUTPUT%"
                echo.>> "%OUTPUT%"
                type "!FILEPATH!" >> "%OUTPUT%"
                echo.>> "%OUTPUT%"
                echo.>> "%OUTPUT%"
                echo --->> "%OUTPUT%"
                echo.>> "%OUTPUT%"
            )
        )
    ) else (
        echo   [No steering dir] !REPO_NAME!
    )
)

echo.
echo [build-cli-steering] Output: %OUTPUT%
echo [build-cli-steering] Done.

endlocal
